services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoTurboHelper\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoTurboHelperBundle.php}
